-- GERADO por tools/export_tfs.py a partir de data/jutsus/*.json. NAO EDITE A MAO.
-- Regenerar: python3 tools/export_tfs.py (e .venv/bin/python tools/spr/gen_jutsu_icons.py
-- para a folha client-otc/data/images/game/spells/jutsus.png, que precisa da MESMA ordem).
--
-- ENCODING: arquivo ASCII puro. As fontes do OTClient sao bitmaps indexados por byte,
-- entao acentos vao como escapes \xNN em cp1252 (mesma regra de naruto_theme.lua).

-- Ajustes da folha de icones (mesmo formato de SpelllistSettings em gamelib/spells.lua).
NarutoSpelllistProfile = 'Shinobi'
NarutoSpelllistSettings = {
    iconFile = '/images/game/spells/jutsus',
    iconsForGameCooldown = '/images/game/spells/jutsus',
    iconSize = { width = 32, height = 32 },
    iconSizeCooldown = { width = 32, height = 32 },
    spellListWidth = 210,
    spellWindowWidth = 550,
}

-- [nome do jutsu] = posicao na folha jutsus.png; x = indice * 32, y = 0.
NarutoSpellIcons = {
    ['Katon: Grande Bola de Fogo'] = { x = 0, y = 0, index = 0 },
    ['Agulhas Incendi\xE1rias'] = { x = 32, y = 0, index = 1 },
    ['Katon: Sopro de Brasas'] = { x = 64, y = 0, index = 2 },
    ['Katon: Flores de F\xEAnix'] = { x = 96, y = 0, index = 3 },
    ['Katon: Anel de Chamas'] = { x = 128, y = 0, index = 4 },
    ['Katon: Drag\xE3o de Fogo'] = { x = 160, y = 0, index = 5 },
    ['Suiton: Proj\xE9til de \xC1gua'] = { x = 192, y = 0, index = 6 },
    ['Suiton: N\xE9voa Cortante'] = { x = 224, y = 0, index = 7 },
    ['Suiton: Pris\xE3o de \xC1gua'] = { x = 256, y = 0, index = 8 },
    ['Suiton: Drag\xE3o de \xC1gua'] = { x = 288, y = 0, index = 9 },
    ['Suiton: V\xF3rtice Devorador'] = { x = 320, y = 0, index = 10 },
    ['Raio Selado'] = { x = 352, y = 0, index = 11 },
    ['Raiton: Agulha de Raio'] = { x = 384, y = 0, index = 12 },
    ['Raiton: Corrente Est\xE1tica'] = { x = 416, y = 0, index = 13 },
    ['L\xE2mina Rel\xE2mpago'] = { x = 448, y = 0, index = 14 },
    ['Raiton: Lan\xE7a do Rel\xE2mpago'] = { x = 480, y = 0, index = 15 },
    ['Raiton: Armadura El\xE9trica'] = { x = 512, y = 0, index = 16 },
    ['Bainha El\xE9trica'] = { x = 544, y = 0, index = 17 },
    ['Raiton: Punho do Trov\xE3o'] = { x = 576, y = 0, index = 18 },
    ['Doton: Bala de Lama'] = { x = 608, y = 0, index = 19 },
    ['Doton: Muralha de Pedra'] = { x = 640, y = 0, index = 20 },
    ['Doton: Estacas de Terra'] = { x = 672, y = 0, index = 21 },
    ['Doton: Colapso do Terreno'] = { x = 704, y = 0, index = 22 },
    ['Fuuton: L\xE2mina de Vento'] = { x = 736, y = 0, index = 23 },
    ['Rasteira de Vento Leve'] = { x = 768, y = 0, index = 24 },
    ['Fuuton: Rajada Cortante'] = { x = 800, y = 0, index = 25 },
    ['Fuuton: Redemoinho Pris\xE3o'] = { x = 832, y = 0, index = 26 },
    ['Fuuton: Tornado Cortante'] = { x = 864, y = 0, index = 27 },
    ['Agulhas Multiplas'] = { x = 896, y = 0, index = 28 },
    ['Chute Ascendente'] = { x = 928, y = 0, index = 29 },
    ['Kunai Marcada'] = { x = 960, y = 0, index = 30 },
    ['Punho Suave'] = { x = 992, y = 0, index = 31 },
    ['Kawarimi no Jutsu'] = { x = 1024, y = 0, index = 32 },
    ['Palma Gentil'] = { x = 1056, y = 0, index = 33 },
    ['Foco Ocular'] = { x = 1088, y = 0, index = 34 },
    ['Bunshin no Jutsu'] = { x = 1120, y = 0, index = 35 },
    ['Vigor Teimoso'] = { x = 1152, y = 0, index = 36 },
    ['Vis\xE3o de Alcance Total'] = { x = 1184, y = 0, index = 37 },
    ['Clone Sombrio'] = { x = 1216, y = 0, index = 38 },
    ['Shousen: Palma Curativa'] = { x = 1248, y = 0, index = 39 },
    ['Salto do Selo'] = { x = 1280, y = 0, index = 40 },
    ['Barreira Protetora'] = { x = 1312, y = 0, index = 41 },
    ['Chute Giratorio'] = { x = 1344, y = 0, index = 42 },
    ['Contra-Ataque Calculado'] = { x = 1376, y = 0, index = 43 },
    ['Soco Monstruoso'] = { x = 1408, y = 0, index = 44 },
    ['Soco da Juventude'] = { x = 1440, y = 0, index = 45 },
    ['Selo de Exorcismo'] = { x = 1472, y = 0, index = 46 },
    ['Corte Duplo'] = { x = 1504, y = 0, index = 47 },
    ['Lamina de Chakra'] = { x = 1536, y = 0, index = 48 },
    ['Palma Dupla'] = { x = 1568, y = 0, index = 49 },
    ['Doku: N\xE9voa Venenosa'] = { x = 1600, y = 0, index = 50 },
    ['C\xEDrculo de Selos'] = { x = 1632, y = 0, index = 51 },
    ['Explos\xE3o do Selo'] = { x = 1664, y = 0, index = 52 },
    ['Fuuin: Selo de Conten\xE7\xE3o'] = { x = 1696, y = 0, index = 53 },
}

-- Mesmo formato de SpellInfo['Default']. 'words' sao os selos (= words do spells.xml).
NarutoSpellInfo = {
    ['Katon: Grande Bola de Fogo'] = { id = 900, name = 'Katon: Grande Bola de Fogo', words = 'katon goukakyuu', type = 'Instant', level = 1, mana = 15, soul = 0, maglevel = 0, icon = 'katon_goukakyuu', clientId = 0, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 5, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Dispara uma bola de fogo que explode no impacto.' },
    ['Agulhas Incendi\xE1rias'] = { id = 901, name = 'Agulhas Incendi\xE1rias', words = 'agulhas incendiarias', type = 'Instant', level = 5, mana = 14, soul = 0, maglevel = 0, icon = 'agulhas_incendiarias', clientId = 1, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 5, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Agulhas finas envoltas em chamas, lan\xE7adas com precis\xE3o cir\xFArgica.' },
    ['Katon: Sopro de Brasas'] = { id = 902, name = 'Katon: Sopro de Brasas', words = 'katon sopro brasas', type = 'Instant', level = 6, mana = 18, soul = 0, maglevel = 0, icon = 'katon_sopro_brasas', clientId = 2, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 2, exhaustion = 3000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um sopro curto de brasas que cobre os tiles imediatamente \xE0 frente.' },
    ['Katon: Flores de F\xEAnix'] = { id = 903, name = 'Katon: Flores de F\xEAnix', words = 'katon housenka', type = 'Instant', level = 12, mana = 30, soul = 0, maglevel = 0, icon = 'katon_housenka', clientId = 3, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 3, exhaustion = 4000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'V\xE1rios proj\xE9teis de fogo em cone \xE0 frente.' },
    ['Katon: Anel de Chamas'] = { id = 904, name = 'Katon: Anel de Chamas', words = 'katon anel chamas', type = 'Instant', level = 20, mana = 42, soul = 0, maglevel = 0, icon = 'katon_anel_chamas', clientId = 4, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 6000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um anel de fogo explode ao redor do conjurador, queimando tudo em volta.' },
    ['Katon: Drag\xE3o de Fogo'] = { id = 905, name = 'Katon: Drag\xE3o de Fogo', words = 'katon karyuu endan', type = 'Instant', level = 35, mana = 60, soul = 0, maglevel = 0, icon = 'katon_karyuu_endan', clientId = 5, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 6, exhaustion = 8000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um drag\xE3o de chamas em linha reta, atravessa inimigos.' },
    ['Suiton: Proj\xE9til de \xC1gua'] = { id = 906, name = 'Suiton: Proj\xE9til de \xC1gua', words = 'suiton mizudan', type = 'Instant', level = 1, mana = 12, soul = 0, maglevel = 0, icon = 'suiton_mizudan', clientId = 6, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 6, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Bala de \xE1gua comprimida.' },
    ['Suiton: N\xE9voa Cortante'] = { id = 907, name = 'Suiton: N\xE9voa Cortante', words = 'suiton nevoa cortante', type = 'Instant', level = 6, mana = 17, soul = 0, maglevel = 0, icon = 'suiton_nevoa_cortante', clientId = 7, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 2, exhaustion = 3000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Got\xEDculas afiadas suspensas no ar cortam quem estiver \xE0 frente.' },
    ['Suiton: Pris\xE3o de \xC1gua'] = { id = 908, name = 'Suiton: Pris\xE3o de \xC1gua', words = 'suiton prisao agua', type = 'Instant', level = 22, mana = 38, soul = 0, maglevel = 0, icon = 'suiton_prisao_agua', clientId = 8, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 3, exhaustion = 7000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma esfera de \xE1gua prende o alvo no lugar e o sufoca lentamente.' },
    ['Suiton: Drag\xE3o de \xC1gua'] = { id = 909, name = 'Suiton: Drag\xE3o de \xC1gua', words = 'suiton suiryuudan', type = 'Instant', level = 25, mana = 45, soul = 0, maglevel = 0, icon = 'suiton_suiryuudan', clientId = 9, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 5, exhaustion = 6000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Onda em linha que empurra e desacelera.' },
    ['Suiton: V\xF3rtice Devorador'] = { id = 910, name = 'Suiton: V\xF3rtice Devorador', words = 'suiton vortice devorador', type = 'Instant', level = 45, mana = 72, soul = 0, maglevel = 0, icon = 'suiton_vortice_devorador', clientId = 10, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 5, exhaustion = 9000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um redemoinho colossal engole a \xE1rea e arrasta tudo para o centro.' },
    ['Raio Selado'] = { id = 911, name = 'Raio Selado', words = 'raio selado', type = 'Instant', level = 1, mana = 15, soul = 0, maglevel = 0, icon = 'raio_selado', clientId = 11, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 5, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um raio fino disparado com precisao cirurgica.' },
    ['Raiton: Agulha de Raio'] = { id = 912, name = 'Raiton: Agulha de Raio', words = 'raiton hari', type = 'Instant', level = 1, mana = 14, soul = 0, maglevel = 0, icon = 'raiton_hari', clientId = 12, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 7, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Agulha el\xE9trica r\xE1pida, pode paralisar.' },
    ['Raiton: Corrente Est\xE1tica'] = { id = 913, name = 'Raiton: Corrente Est\xE1tica', words = 'raiton corrente estatica', type = 'Instant', level = 6, mana = 16, soul = 0, maglevel = 0, icon = 'raiton_corrente_estatica', clientId = 13, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 2500, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'A eletricidade salta em cruz pelo ch\xE3o a partir do conjurador.' },
    ['L\xE2mina Rel\xE2mpago'] = { id = 914, name = 'L\xE2mina Rel\xE2mpago', words = 'lamina relampago pessoal', type = 'Instant', level = 10, mana = 22, soul = 0, maglevel = 0, icon = 'lamina_relampago_pessoal', clientId = 14, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 1, exhaustion = 2200, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um corte de l\xE2mina eletrificada, r\xE1pido o bastante para atordoar.' },
    ['Raiton: Lan\xE7a do Rel\xE2mpago'] = { id = 915, name = 'Raiton: Lan\xE7a do Rel\xE2mpago', words = 'raiton lanca relampago', type = 'Instant', level = 18, mana = 40, soul = 0, maglevel = 0, icon = 'raiton_lanca_relampago', clientId = 15, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 5, exhaustion = 5500, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um raio cont\xEDnuo perfura em linha reta e atravessa v\xE1rios inimigos.' },
    ['Raiton: Armadura El\xE9trica'] = { id = 916, name = 'Raiton: Armadura El\xE9trica', words = 'raiton armadura eletrica', type = 'Instant', level = 24, mana = 36, soul = 0, maglevel = 0, icon = 'raiton_armadura_eletrica', clientId = 16, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 16000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma casca de eletricidade cobre o corpo, acelerando a recupera\xE7\xE3o enquanto dura.' },
    ['Bainha El\xE9trica'] = { id = 917, name = 'Bainha El\xE9trica', words = 'bainha eletrica', type = 'Instant', level = 26, mana = 34, soul = 0, maglevel = 0, icon = 'bainha_eletrica', clientId = 17, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 16000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'A l\xE2mina vibra com eletricidade, formando uma bainha que acelera a recupera\xE7\xE3o do usu\xE1rio.' },
    ['Raiton: Punho do Trov\xE3o'] = { id = 918, name = 'Raiton: Punho do Trov\xE3o', words = 'raiton punho trovao', type = 'Instant', level = 30, mana = 50, soul = 0, maglevel = 0, icon = 'raiton_punho_trovao', clientId = 18, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 1, exhaustion = 7000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Concentra o raio na palma da m\xE3o e desfere um golpe devastador no alvo adjacente.' },
    ['Doton: Bala de Lama'] = { id = 919, name = 'Doton: Bala de Lama', words = 'doton bala lama', type = 'Instant', level = 1, mana = 14, soul = 0, maglevel = 0, icon = 'doton_bala_lama', clientId = 19, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 6, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma bala de lama endurecida disparada em alta velocidade.' },
    ['Doton: Muralha de Pedra'] = { id = 920, name = 'Doton: Muralha de Pedra', words = 'doton muralha pedra', type = 'Instant', level = 8, mana = 28, soul = 0, maglevel = 0, icon = 'doton_muralha_pedra', clientId = 20, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 14000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Ergue uma casca de rocha ao redor do corpo, endurecendo a pele por alguns segundos.' },
    ['Doton: Estacas de Terra'] = { id = 921, name = 'Doton: Estacas de Terra', words = 'doton estacas terra', type = 'Instant', level = 22, mana = 40, soul = 0, maglevel = 0, icon = 'doton_estacas_terra', clientId = 21, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 4, exhaustion = 6000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Estacas de pedra irrompem do ch\xE3o em cruz, prendendo quem estiver em cima.' },
    ['Doton: Colapso do Terreno'] = { id = 922, name = 'Doton: Colapso do Terreno', words = 'doton colapso terreno', type = 'Instant', level = 48, mana = 70, soul = 0, maglevel = 0, icon = 'doton_colapso_terreno', clientId = 22, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 5, exhaustion = 9000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'O solo afunda num raio amplo e esmaga tudo que est\xE1 dentro da cratera.' },
    ['Fuuton: L\xE2mina de Vento'] = { id = 923, name = 'Fuuton: L\xE2mina de Vento', words = 'fuuton lamina vento', type = 'Instant', level = 1, mana = 13, soul = 0, maglevel = 0, icon = 'fuuton_lamina_vento', clientId = 23, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 6, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma l\xE2mina de ar comprimido cortando em linha reta at\xE9 o alvo.' },
    ['Rasteira de Vento Leve'] = { id = 924, name = 'Rasteira de Vento Leve', words = 'fuuton rasteira vento', type = 'Instant', level = 4, mana = 14, soul = 0, maglevel = 0, icon = 'fuuton_rasteira_vento', clientId = 24, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 3000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma rasteira refor\xE7ada por uma leve corrente de vento, desequilibra o alvo.' },
    ['Fuuton: Rajada Cortante'] = { id = 925, name = 'Fuuton: Rajada Cortante', words = 'fuuton rajada cortante', type = 'Instant', level = 16, mana = 34, soul = 0, maglevel = 0, icon = 'fuuton_rajada_cortante', clientId = 25, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 3, exhaustion = 4500, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma rajada em leque que retalha tudo \xE0 frente e desequilibra os atingidos.' },
    ['Fuuton: Redemoinho Pris\xE3o'] = { id = 926, name = 'Fuuton: Redemoinho Pris\xE3o', words = 'fuuton redemoinho prisao', type = 'Instant', level = 23, mana = 38, soul = 0, maglevel = 0, icon = 'fuuton_redemoinho_prisao', clientId = 26, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 4, exhaustion = 9000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um redemoinho de vento prende o alvo no ar, impedindo qualquer movimento.' },
    ['Fuuton: Tornado Cortante'] = { id = 927, name = 'Fuuton: Tornado Cortante', words = 'fuuton tornado cortante', type = 'Instant', level = 36, mana = 62, soul = 0, maglevel = 0, icon = 'fuuton_tornado_cortante', clientId = 27, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 6, exhaustion = 8000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma coluna de vento afiado que avan\xE7a em linha reta, despeda\xE7ando tudo no caminho.' },
    ['Agulhas Multiplas'] = { id = 928, name = 'Agulhas Multiplas', words = 'agulhas multiplas', type = 'Instant', level = 1, mana = 14, soul = 0, maglevel = 0, icon = 'agulhas_multiplas', clientId = 28, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 5, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma saraivada de agulhas de metal lancadas contra o alvo.' },
    ['Chute Ascendente'] = { id = 929, name = 'Chute Ascendente', words = 'chute ascendente', type = 'Instant', level = 2, mana = 16, soul = 0, maglevel = 0, icon = 'chute_ascendente', clientId = 29, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 1, exhaustion = 2500, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um chute ascendente que desequilibra o alvo e abre espa\xE7o para o pr\xF3ximo golpe.' },
    ['Kunai Marcada'] = { id = 930, name = 'Kunai Marcada', words = 'kunai marcada', type = 'Instant', level = 3, mana = 14, soul = 0, maglevel = 0, icon = 'kunai_marcada', clientId = 30, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 7, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma kunai selada, lan\xE7ada para marcar o alvo e permitir um salto instant\xE2neo depois.' },
    ['Punho Suave'] = { id = 931, name = 'Punho Suave', words = 'punho suave', type = 'Instant', level = 3, mana = 12, soul = 0, maglevel = 0, icon = 'punho_suave', clientId = 31, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 1, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Golpe preciso que atinge pontos de chakra e retarda o alvo.' },
    ['Kawarimi no Jutsu'] = { id = 932, name = 'Kawarimi no Jutsu', words = 'kawarimi', type = 'Instant', level = 5, mana = 20, soul = 0, maglevel = 0, icon = 'kawarimi', clientId = 32, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 12000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Substitui\xE7\xE3o: fica invulner\xE1vel por 1s e teleporta 2 tiles para tr\xE1s.' },
    ['Palma Gentil'] = { id = 933, name = 'Palma Gentil', words = 'palma gentil', type = 'Instant', level = 5, mana = 16, soul = 0, maglevel = 0, icon = 'palma_gentil', clientId = 33, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 1, exhaustion = 2000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um toque preciso em pontos de chakra que trava os movimentos do alvo.' },
    ['Foco Ocular'] = { id = 934, name = 'Foco Ocular', words = 'foco ocular', type = 'Instant', level = 7, mana = 26, soul = 0, maglevel = 0, icon = 'foco_ocular', clientId = 34, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 14000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Foco extremo que antecipa o pr\xF3ximo golpe do inimigo, abrindo brechas para contra-atacar.' },
    ['Bunshin no Jutsu'] = { id = 935, name = 'Bunshin no Jutsu', words = 'bunshin', type = 'Instant', level = 8, mana = 25, soul = 0, maglevel = 0, icon = 'bunshin', clientId = 35, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 15000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Cria 2 clones que distraem monstros por 6s.' },
    ['Vigor Teimoso'] = { id = 936, name = 'Vigor Teimoso', words = 'vigor teimoso', type = 'Instant', level = 9, mana = 30, soul = 0, maglevel = 0, icon = 'vigor_teimoso', clientId = 36, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 18000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Determina\xE7\xE3o teimosa que acelera a recupera\xE7\xE3o do pr\xF3prio corpo em combate.' },
    ['Vis\xE3o de Alcance Total'] = { id = 937, name = 'Vis\xE3o de Alcance Total', words = 'visao total', type = 'Instant', level = 9, mana = 22, soul = 0, maglevel = 0, icon = 'visao_total', clientId = 37, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 16000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Vis\xE3o que enxerga os pontos vitais de chakra do inimigo, refinando cada golpe seguinte.' },
    ['Clone Sombrio'] = { id = 938, name = 'Clone Sombrio', words = 'clone sombrio', type = 'Instant', level = 10, mana = 35, soul = 0, maglevel = 0, icon = 'clone_sombrio', clientId = 38, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 20000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Invoca dois clones de sombra que distraem os inimigos por um instante.' },
    ['Shousen: Palma Curativa'] = { id = 939, name = 'Shousen: Palma Curativa', words = 'shousen', type = 'Instant', level = 10, mana = 35, soul = 0, maglevel = 0, icon = 'shousen', clientId = 39, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 10000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Cura o pr\xF3prio HP ao longo de 5s.' },
    ['Salto do Selo'] = { id = 940, name = 'Salto do Selo', words = 'salto do selo', type = 'Instant', level = 12, mana = 28, soul = 0, maglevel = 0, icon = 'salto_do_selo', clientId = 40, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 10000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Teleporta instantaneamente at\xE9 a \xFAltima kunai marcada lan\xE7ada.' },
    ['Barreira Protetora'] = { id = 941, name = 'Barreira Protetora', words = 'barreira protetora', type = 'Instant', level = 14, mana = 38, soul = 0, maglevel = 0, icon = 'barreira_protetora', clientId = 41, group = { [2] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 18000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma barreira de chakra selado que absorve parte do dano recebido.' },
    ['Chute Giratorio'] = { id = 942, name = 'Chute Giratorio', words = 'chute giratorio', type = 'Instant', level = 14, mana = 22, soul = 0, maglevel = 0, icon = 'chute_giratorio', clientId = 42, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 1, exhaustion = 4000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Chute em rotacao que acerta todos ao redor.' },
    ['Contra-Ataque Calculado'] = { id = 943, name = 'Contra-Ataque Calculado', words = 'contra ataque calculado', type = 'Instant', level = 15, mana = 20, soul = 0, maglevel = 0, icon = 'contra_ataque_calculado', clientId = 43, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 1, exhaustion = 6000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um golpe r\xE1pido que pune a brecha aberta pelo inimigo ap\xF3s prever seu ataque.' },
    ['Soco Monstruoso'] = { id = 944, name = 'Soco Monstruoso', words = 'soco monstruoso', type = 'Instant', level = 16, mana = 24, soul = 0, maglevel = 0, icon = 'soco_monstruoso', clientId = 44, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 1, exhaustion = 4000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um soco de for\xE7a monstruosa que racha o ch\xE3o ao redor do impacto.' },
    ['Soco da Juventude'] = { id = 945, name = 'Soco da Juventude', words = 'soco da juventude', type = 'Instant', level = 18, mana = 26, soul = 0, maglevel = 0, icon = 'soco_da_juventude', clientId = 45, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 1, exhaustion = 4500, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um soco carregado de puro vigor f\xEDsico, sem chakra nenhum envolvido.' },
    ['Selo de Exorcismo'] = { id = 946, name = 'Selo de Exorcismo', words = 'selo de exorcismo', type = 'Instant', level = 19, mana = 34, soul = 0, maglevel = 0, icon = 'selo_de_exorcismo', clientId = 46, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 4, exhaustion = 6000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um selo cerimonial que perfura o chakra do alvo, travando seus movimentos.' },
    ['Corte Duplo'] = { id = 947, name = 'Corte Duplo', words = 'corte duplo', type = 'Instant', level = 20, mana = 32, soul = 0, maglevel = 0, icon = 'corte_duplo', clientId = 47, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 2, exhaustion = 4500, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Dois cortes sucessivos de l\xE2mina em um golpe s\xF3, cobrindo um arco \xE0 frente.' },
    ['Lamina de Chakra'] = { id = 948, name = 'Lamina de Chakra', words = 'lamina chakra', type = 'Instant', level = 20, mana = 28, soul = 0, maglevel = 0, icon = 'lamina_chakra', clientId = 48, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 5, exhaustion = 5000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma lamina invisivel de chakra que atravessa varios inimigos em linha reta.' },
    ['Palma Dupla'] = { id = 949, name = 'Palma Dupla', words = 'palma dupla', type = 'Instant', level = 24, mana = 36, soul = 0, maglevel = 0, icon = 'palma_dupla', clientId = 49, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 2, exhaustion = 5000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Uma sequ\xEAncia dupla de palmas que atinge tudo \xE0 frente em rajada.' },
    ['Doku: N\xE9voa Venenosa'] = { id = 950, name = 'Doku: N\xE9voa Venenosa', words = 'doku kiri', type = 'Instant', level = 25, mana = 46, soul = 0, maglevel = 0, icon = 'doku_kiri', clientId = 50, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 2, exhaustion = 6000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Exala uma n\xE9voa roxa ao redor do conjurador; quem respira sai envenenado.' },
    ['C\xEDrculo de Selos'] = { id = 951, name = 'C\xEDrculo de Selos', words = 'circulo de selos', type = 'Instant', level = 27, mana = 44, soul = 0, maglevel = 0, icon = 'circulo_de_selos', clientId = 51, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 3, exhaustion = 8000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Um c\xEDrculo de selos surge no ch\xE3o, prendendo todos que estiverem dentro.' },
    ['Explos\xE3o do Selo'] = { id = 952, name = 'Explos\xE3o do Selo', words = 'explosao do selo', type = 'Instant', level = 28, mana = 46, soul = 0, maglevel = 0, icon = 'explosao_do_selo', clientId = 52, group = { [1] = 1000 }, needTarget = false, parameter = false, range = 6, exhaustion = 7000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Detona o selo de uma kunai marcada \xE0 dist\xE2ncia, sem precisar estar perto.' },
    ['Fuuin: Selo de Conten\xE7\xE3o'] = { id = 953, name = 'Fuuin: Selo de Conten\xE7\xE3o', words = 'fuuin contencao', type = 'Instant', level = 40, mana = 45, soul = 0, maglevel = 0, icon = 'fuuin_contencao', clientId = 53, group = { [1] = 1000 }, needTarget = true, parameter = false, range = 4, exhaustion = 12000, premium = false, vocations = { 1, 2, 3, 4, 5, 6, 7, 8 }, special = false, source = 0, description = 'Selo de papel que trava os m\xFAsculos do alvo por alguns segundos.' },
}

-- Vilas por vocation_id (o que player:getVocation() devolve). setName e o nome do
-- conjunto de hotkeys do game_actionbar: ASCII puro, porque vira chave no JSON.
NarutoVillages = {
    [1] = { id = 'leaf', name = 'Vila da Folha', setName = 'Vila da Folha', element = 'katon' },
    [2] = { id = 'mist', name = 'Vila da N\xE9voa', setName = 'Vila da Nevoa', element = 'suiton' },
    [3] = { id = 'cloud', name = 'Vila da Nuvem', setName = 'Vila da Nuvem', element = 'raiton' },
    [4] = { id = 'sand', name = 'Vila da Areia', setName = 'Vila da Areia', element = 'fuuton' },
}

-- Ordem sugerida da barra de acao: por level exigido, depois nome.
NarutoJutsuOrder = {
    'Agulhas Multiplas',
    'Doton: Bala de Lama',
    'Fuuton: L\xE2mina de Vento',
    'Katon: Grande Bola de Fogo',
    'Raio Selado',
    'Raiton: Agulha de Raio',
    'Suiton: Proj\xE9til de \xC1gua',
    'Chute Ascendente',
    'Kunai Marcada',
    'Punho Suave',
    'Rasteira de Vento Leve',
    'Agulhas Incendi\xE1rias',
    'Kawarimi no Jutsu',
    'Palma Gentil',
    'Katon: Sopro de Brasas',
    'Raiton: Corrente Est\xE1tica',
    'Suiton: N\xE9voa Cortante',
    'Foco Ocular',
    'Bunshin no Jutsu',
    'Doton: Muralha de Pedra',
    'Vigor Teimoso',
    'Vis\xE3o de Alcance Total',
    'Clone Sombrio',
    'L\xE2mina Rel\xE2mpago',
    'Shousen: Palma Curativa',
    'Katon: Flores de F\xEAnix',
    'Salto do Selo',
    'Barreira Protetora',
    'Chute Giratorio',
    'Contra-Ataque Calculado',
    'Fuuton: Rajada Cortante',
    'Soco Monstruoso',
    'Raiton: Lan\xE7a do Rel\xE2mpago',
    'Soco da Juventude',
    'Selo de Exorcismo',
    'Corte Duplo',
    'Katon: Anel de Chamas',
    'Lamina de Chakra',
    'Doton: Estacas de Terra',
    'Suiton: Pris\xE3o de \xC1gua',
    'Fuuton: Redemoinho Pris\xE3o',
    'Palma Dupla',
    'Raiton: Armadura El\xE9trica',
    'Doku: N\xE9voa Venenosa',
    'Suiton: Drag\xE3o de \xC1gua',
    'Bainha El\xE9trica',
    'C\xEDrculo de Selos',
    'Explos\xE3o do Selo',
    'Raiton: Punho do Trov\xE3o',
    'Katon: Drag\xE3o de Fogo',
    'Fuuton: Tornado Cortante',
    'Fuuin: Selo de Conten\xE7\xE3o',
    'Suiton: V\xF3rtice Devorador',
    'Doton: Colapso do Terreno',
}

-- Jutsus por PERSONAGEM (looktype 900-909): ver data/characters.json. Preenche a barra
-- de acao quando o jogador troca de personagem (naruto_jutsus.lua, onOutfitChange).
NarutoCharacterJutsus = {
    [900] = { id = 'genin_laranja', name = 'Genin Laranja', village = 'leaf', words = { 'clone sombrio', 'kawarimi', 'fuuton rasteira vento', 'vigor teimoso' } },
    [901] = { id = 'genin_uchiha', name = 'Genin Uchiha', village = 'leaf', words = { 'foco ocular', 'agulhas incendiarias', 'contra ataque calculado', 'kawarimi' } },
    [902] = { id = 'kunoichi_rosa', name = 'Kunoichi Rosa', village = 'leaf', words = { 'shousen', 'punho suave', 'soco monstruoso', 'kawarimi' } },
    [903] = { id = 'herdeira_hyuga', name = 'Herdeira Hyuga', village = 'mist', words = { 'palma gentil', 'fuuin contencao', 'visao total', 'palma dupla' } },
    [905] = { id = 'kunoichi_armas', name = 'Kunoichi das Armas', village = 'mist', words = { 'agulhas multiplas', 'lamina chakra', 'doku kiri', 'bunshin' } },
    [904] = { id = 'ninja_verde', name = 'Ninja Verde', village = 'cloud', words = { 'punho suave', 'chute giratorio', 'soco da juventude', 'chute ascendente' } },
    [909] = { id = 'ninja_abelha', name = 'Ninja Abelha', village = 'cloud', words = { 'lamina relampago pessoal', 'corte duplo', 'bainha eletrica', 'raio selado' } },
    [907] = { id = 'sabio_loiro', name = 'Sabio Loiro', village = 'sand', words = { 'kawarimi', 'kunai marcada', 'salto do selo', 'explosao do selo' } },
    [908] = { id = 'sabio_cerimonial', name = 'Sabio Cerimonial', village = 'sand', words = { 'fuuin contencao', 'barreira protetora', 'selo de exorcismo', 'circulo de selos' } },
}
